# Generated by Django 4.0.6 on 2022-07-09 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('student_type', models.CharField(choices=[('bakalavr', 'bakalavr'), ('magistr', 'magistr')], default='bakalavr', max_length=120)),
                ('otm', models.CharField(max_length=250)),
                ('summa', models.PositiveIntegerField(blank=True, null=True)),
                ('kontrakt', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metsenat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('homiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.sponsor')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
