# Generated by Django 4.0.6 on 2022-07-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('students', '0002_remove_metsenat_homiy_metsenat_homiy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metsenat',
            name='homiy',
        ),
        migrations.AddField(
            model_name='metsenat',
            name='homiy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.sponsor'),
            preserve_default=False,
        ),
    ]
