# Generated by Django 4.0.6 on 2022-07-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('students', '0003_remove_metsenat_homiy_metsenat_homiy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metsenat',
            name='homiy',
        ),
        migrations.AddField(
            model_name='metsenat',
            name='homiy',
            field=models.ManyToManyField(to='blog.sponsor'),
        ),
    ]
