# Generated by Django 4.0.6 on 2022-07-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_metsenat_homiy_metsenat_homiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metsenat',
            name='summa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
