# Generated by Django 4.0.6 on 2022-07-12 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_sponsor_created_at'),
        ('students', '0005_alter_metsenat_summa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metsenat',
            old_name='talaba',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='metsenat',
            name='homiy',
        ),
        migrations.RemoveField(
            model_name='student',
            name='summa',
        ),
        migrations.AddField(
            model_name='metsenat',
            name='sponsor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.sponsor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metsenat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='metsenat',
            name='summa',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
