# Generated by Django 4.0.6 on 2022-07-09 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=14)),
                ('summa', models.PositiveIntegerField()),
                ('holati', models.CharField(choices=[('yangi', 'yangi'), ('moderatsiyada', 'moderatsiyada'), ('tasdiqlangan', 'tasdiqlangan'), ('bekor qilingan', 'bekor qilingan')], default='yanngi', max_length=120)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tashkilot_nomi', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
